React state with Mats
Technigo/project-survey pull request #116
Opened 2020-10-25 12:32 UTC by mats-johansen

Link to my deployed project:

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2020-10-29 19:17 UTC, petrame approved these changes
Hello Mats! Great job with the survey!
I had no problem reading the code, although some comments here and there for future you wouldn't hurt :)
I think the design is cool. The font, image and button fit well together.
Also, great job with the required attribute, I know many of us struggled with that.

2020-10-29 19:17 UTC, petrame commented on code/src/index.css
> +}
Well structured css code and easy to read.

2020-11-03 13:44 UTC, HIPPIEKICK commented on code/src/App.js
> +  }
semicolons

2020-11-03 13:45 UTC, HIPPIEKICK commented on code/src/InputSelect.js
> +}
semicolons

2020-11-03 13:47 UTC, HIPPIEKICK requested changes
Take a stand on whether you're using semicolons or not - either everywhere or not at all :) Changing to CR until it's consistent. Also - I saw that you still have issues with VSC formatting (as in `InputRadio.js`). Did you get any clarity on that?

2020-11-03 13:48 UTC, HIPPIEKICK commented on README.md
> +Had some issues understandning state and styling the forms & radio-buttons in a nice looking way. But progress is being made!
Agree on the nice design!

2020-11-04 09:46 UTC, mats-johansen commented
> Take a stand on whether you're using semicolons or not - either everywhere or not at all :) Changing to CR until it's consistent. Also - I saw that you still have issues with VSC formatting (as in `InputRadio.js`). Did you get any clarity on that?

Oh noticed that I was inconsistent on the semicolons now! No still working on the formatting issue, still have to change between javascript and javascript react when saving. Hopefully it will start working after the next troubleshoot session haha

2020-11-04 16:30 UTC, HIPPIEKICK commented
> > Take a stand on whether you're using semicolons or not - either everywhere or not at all :) Changing to CR until it's consistent. Also - I saw that you still have issues with VSC formatting (as in `InputRadio.js`). Did you get any clarity on that?
> 
> Oh noticed that I was inconsistent on the semicolons now! No still working on the formatting issue, still have to change between javascript and javascript react when saving. Hopefully it will start working after the next troubleshoot session haha

Did you try to update / reinstall VSC? Uninstalling formatters (like prettier)?

2020-11-04 16:30 UTC, HIPPIEKICK approved these changes

2020-11-05 09:41 UTC, HIPPIEKICK commented
Regarding formatting issues, take a look at this: https://www.digitalocean.com/community/tutorials/how-to-format-code-with-prettier-in-visual-studio-code

> Note: If you do not see a prompt for selecting a default format, you can manually change this in your Settings. Set Editor: Default Formatter to ebsenp.prettier-vscode.

2021-03-09 11:25 UTC, closed without merging