Project survey - Emma
Technigo/project-survey pull request #130
Opened 2020-10-25 20:21 UTC by emma-tech

**Link to my deployed project:** 
https://project-survey-favorite-plants.netlify.app/

**My reflections on how this week's project turned out:** 
I wish I would've had more time to do some more advanced features and styling for my form, but I'm happy with the result and that I've really practiced in using several components and files for styling 👍 

**Things I'd like to have clarified or explained in more detail:**
I still think the use of props is hard to grasp... is there any part in the code I could've simplified even more? Are there any "unnecessary" code I should be aware of? :)

2020-10-28 17:59 UTC, evelinabe reviewed
Hi Emma!

You're survey is really well styled, I'm impressed that you took the time to make it responsive as well. Your code is well structured and the comments are just enough to make the code easy to read. Well done!

There's just a small thing I would like you to fix, and that's the indentation only thing I would like you to fix is the indentation in the react-components. I have left some comments for you. 

Besides that, you have a great looking page and easy to read code. Well done!

2020-10-28 17:59 UTC, evelinabe commented on code/src/Components/Form.js
> +    };
Tip: when you only have one argument in a function you can omit the parenthesis.  The function would then look like: 

```
const handleNameInput = inputName => {
          setName(inputName);
},
```

2020-10-28 17:59 UTC, evelinabe commented on code/src/Components/Header.js
> +      />
Indents are missing, and the first attribute should be on a new row as well, like so:

```
<img
        src="../img/hero.jpg"
        className="hero-img"
        alt="Green leaf in a glass vase with water
/>
```

2020-10-28 17:59 UTC, evelinabe commented on code/src/Components/Input.js
> +                <span role="img" aria-label="cactus"> 🌵 </span>
Accessible and cute 💫🏅

2020-10-28 17:59 UTC, evelinabe commented on code/src/Components/Input.js
> +            />
The attributes are missing indents here as well 🤓

2020-10-28 17:59 UTC, evelinabe commented on code/src/Components/Summary.js
> +            <p className="summary-text">Your favorite plant is: {favoritePlant}.</p>
Your class-names are explanatory and consistent, well done!

2020-10-28 17:59 UTC, evelinabe commented on code/src/index.css
> +  -moz-box-sizing: border-box;
Great looking!

2020-10-28 17:59 UTC, evelinabe commented on code/src/styles/form.css
> +  input[type=radio] {
Wow, styled radio-buttons 🏅

2020-10-28 17:59 UTC, evelinabe commented on code/src/styles/form.css
> +  @media screen and (min-width: 280px) {
I'm impressed that you made the page responsive 💥

2020-10-28 17:59 UTC, evelinabe commented on code/src/styles/header.css
> +  }
These could be removed since not in use.

2020-10-28 17:59 UTC, evelinabe commented on code/src/App.js
> +      </div>
Indents are missing.

2020-10-28 18:00 UTC, evelinabe requested changes
Hi Emma!

You're survey is really well styled, I'm impressed that you took the time to make it responsive as well. Your code is well structured and the comments are just enough to make the code easy to read. Well done!

There's just a small thing I would like you to fix, and that's the indentation only thing I would like you to fix is the indentation in the react-components. I have left some comments for you. 

Besides that, you have a great looking page and easy to read code. Well done!

2020-11-06 10:34 UTC, HIPPIEKICK commented on code/src/Components/Form.js
> +    );
What a joy to the eye! Really compact and easy to follow ⭐ Some indentation on the attributes would perfect this

2020-11-06 10:36 UTC, HIPPIEKICK commented on code/src/Components/Radiobuttons.js
> +const favoritePlants = ["Monstera", "Cactus", "Begonia", "Oxalis", "Aloe Vera", "Fiddle Leaf Fig", "Chinese Money Plant", "Philodendron", "Umbrella tree"];
I created a practice for Tjejer Kodar about plants and I had to google what "Palettblad" is called in English because that is my favourite ;)

2020-11-06 10:36 UTC, HIPPIEKICK commented on code/src/Components/Select.js
> +            </select>
Some indentation here as well

2020-11-06 10:39 UTC, HIPPIEKICK commented
> Hi Emma!
> 
> You're survey is really well styled, I'm impressed that you took the time to make it responsive as well. Your code is well structured and the comments are just enough to make the code easy to read. Well done!
> 
> There's just a small thing I would like you to fix, and that's the indentation only thing I would like you to fix is the indentation in the react-components. I have left some comments for you.
> 
> Besides that, you have a great looking page and easy to read code. Well done!

I agree with you @evelinabe , really good structure! Will you change the status to Changes requested for the indentation issues? :)

2020-11-07 15:19 UTC, emma-tech commented
Thank you so much for the nice feedback @evelinabe and @HIPPIEKICK 🤩 The indentation issues are fixed 👍

2020-11-09 10:04 UTC, HIPPIEKICK commented on code/src/Components/Radiobuttons.js
> +                />
This should be indented

2021-03-09 11:25 UTC, closed without merging