Project Survey Sara S
Technigo/project-survey pull request #131
Opened 2020-10-25 20:50 UTC by stjernberg

https://awesome-johnson-68e84f.netlify.app

It was a fun project to do and I've learned so much about react. I really tried out different ways of doing things.

Things I'd like to have clarified or explained in more detail: Best wayd to split the project into components and styles. What data should stay in which component etc.

2020-11-04 18:39 UTC, aagneshansson requested changes
Really great work Sara! Your page looks awesome and so does your code 🌟 
What I do think you may could do is to remove console logs + have a look at the accessibility part! Except of that, really great job and well done 🤩

2020-11-04 18:39 UTC, aagneshansson commented on code/src/App.js
> +    <Form />
Great that you kept your app clean :)

2020-11-04 18:39 UTC, aagneshansson commented on code/src/Components/DessertInput.js
> +    console.log(dessert);
Don't forget to remove the console logs 😄

2020-11-04 18:39 UTC, aagneshansson commented on code/src/Components/DessertInput.js
> +                        required
Unfortunately it seems like they are not required in your site 😢

2020-11-04 18:39 UTC, aagneshansson commented on code/src/Components/DrinksInput.js
> +            : setDrinks([...drinks, drinksValue])
Nice if statement 👍

2020-11-04 18:39 UTC, aagneshansson commented on code/src/Components/DrinksInput.js
> +            <input
Great that you added checkboxes. Unfortunately it seems like they don't work with the screen reader, would be great if you could add accessibility to those  👍 🌟

2020-11-04 18:39 UTC, aagneshansson commented on code/src/Components/Form.js
> +            <h1 className="welcome" tabIndex="0">Welcome to Restaurant Starmountain</h1>
Nice with tabIndex!

2020-11-04 18:39 UTC, aagneshansson commented on code/src/Components/Form.js
> +                setSection={setSection}
Great that you added sections ⭐

2020-11-04 18:39 UTC, aagneshansson commented on code/src/Components/MaincourseInput.js
> +const MaincourseInput = ({ maincourse, setMaincourse }) => {
Great way to handle the props 😃

2020-11-04 18:39 UTC, aagneshansson commented on code/src/Components/Summary.js
> +            <p> {userDrinks.join(', ')}</p>
Great work with a summary page like this!

2020-11-04 18:39 UTC, aagneshansson commented on README.md
> +The way of building this project in small steps helped me understand components and state, how the different components fit together and where the
Really beautiful page Sara, you should be proud of yourself with what you have accomplished with such a short time learning about react 😍 🌟

2020-11-06 12:11 UTC, HIPPIEKICK commented on code/src/Components/Buttons.js
> +const Buttons = props => {
Maybe this component could be called `Button` since it's only one :)

2020-11-06 12:16 UTC, HIPPIEKICK commented on code/src/Components/MaincourseInput.js
> +    </select>
Indentation is a little off here, and remember to always give attributes new lines if there are several of them

2020-11-06 12:17 UTC, HIPPIEKICK commented
I wanna add to the changes Agnes suggested, the usage of semicolons is not consistent, and have another look at the indentation of all files as well :)

2020-11-06 12:20 UTC, HIPPIEKICK requested changes
I wanna add to the changes Agnes suggested, the usage of semicolons is not consistent, and have another look at the indentation of all files as well :)

2020-11-09 10:07 UTC, HIPPIEKICK commented on code/src/Components/DessertInput.js
> +        setDessert(event.target.value);
errant semicolon

2020-11-09 10:07 UTC, HIPPIEKICK commented on code/src/Components/DessertInput.js
> +export default DessertInput;
errant semicolon

2020-11-09 10:09 UTC, HIPPIEKICK commented on code/src/Components/MaincourseInput.js
> +    </select>
```
<select
  value={maincourse}
  onChange={handleMaincourseChange}
  className="drop-down">
  <option value="">Main courses...</option>
  <option value="Salmon">Salmon</option>
  <option value="Vegetarian">Vegetarian</option>
  <option value="Chicken">Chicken</option>
  <option value="Steak">Steak</option>
  <option value="Soup">Soup</option>
</select>
```

2020-11-09 10:09 UTC, HIPPIEKICK commented on code/src/Components/NameInput.js
> +import React from 'react';
errant semicolons in this file as well

2020-11-09 10:09 UTC, HIPPIEKICK commented on code/src/Components/Summary.js
> +import React from 'react';
this too

2020-11-16 08:57 UTC, HIPPIEKICK approved these changes

2021-03-09 11:25 UTC, closed without merging