Amanda Project Week 10
Technigo/project-survey pull request #136
Opened 2020-10-26 11:55 UTC by amandaflod

Link to my deployed project: https://app.netlify.com/sites/eloquent-snyder-48ed94/overview

My reflections on how this week's project turned out: I tried to focus more on the functionality and understanding what I was doing and less on the styling etc. I think it turned out really well!

2020-10-26 15:11 UTC, moablomkvist requested changes
Great work! Love the design and the ambitious summarys. Improve the responsiveness. :)

2020-10-26 15:11 UTC, moablomkvist commented on code/src/summary.css
> +  text-align: center;
Text that is longer than three lines can be difficult to read if it is centered. Try to think like books, they start from the margin on the left. Just a tip from a UX Writer. :)

2020-10-26 15:11 UTC, moablomkvist commented on code/src/summary.js
> +const feelingResponse = feeling => {
Ambitious! Really good work Amanda.

2020-11-06 13:34 UTC, HIPPIEKICK commented on code/public/index.html
> +  <title>Technigo React App</title>
Don't forget to change the title :)

2020-11-06 13:35 UTC, HIPPIEKICK commented on code/src/app.js
> +import React, { useState } from 'react'
Also, try to be consistent with double quotes or single quotes

2020-11-06 13:35 UTC, HIPPIEKICK commented on code/src/app.js
> +import React, { useState } from 'react'
And semicolons

2020-11-06 13:38 UTC, HIPPIEKICK commented on code/src/summary.js
> +}
These could be broken out into their own components, or possibly just be switch statements. That's just a suggestion though

2020-11-06 13:40 UTC, HIPPIEKICK requested changes
Consistency in the usage of semicolons - should be used everywhere or not at all according to code guidelines.

2021-03-11 09:17 UTC, closed without merging