Make sombody's day survey
Technigo/project-survey pull request #142
Opened 2020-10-28 07:16 UTC by BamStugendal

Link to my deployed project:
https://make-somebodys-day.netlify.app/

2020-10-28 15:31 UTC, LillanEriksson requested changes
Nice and clean code, very readable. You could think about commenting your code more to make it even more readable. The page looks really nice, and the theme you chose for your survey is heartwarming :)
I would only like you to go over your code and remove the console logs.

2020-10-28 15:31 UTC, LillanEriksson commented on code/src/Form.js
> +import { FirstQuestion } from './FirstQuestion'
Could it be even clearer if you had named each question-component alike? Like question1, question2 on so on?

2020-10-28 15:31 UTC, LillanEriksson commented on code/src/Form.js
> +
Great that you have a blank line between the import react and the imports of components!

2020-10-28 15:31 UTC, LillanEriksson commented on code/src/Form.js
> +
All console logs should be removed before a pull request :)

2020-10-28 15:31 UTC, LillanEriksson commented on code/src/Header.js
> +    )
The header looks soo nice! But when I viewed the page I was a bit confused over where the questions were, it took me a while to get that I needed to scroll down, I clicked everywhere to se if it was something i should click. Maybe a little notice like "scroll down to answer"? :)

2020-11-09 09:55 UTC, HIPPIEKICK commented on code/src/Summary.js
> +        </section>
Love this summary! 💯

2020-11-09 09:57 UTC, HIPPIEKICK requested changes
Such a sweet survey! Requesting changes because the code is inconsistent regarding the usage of semicolons. They should be used everywhere or not at all.

2021-02-08 10:23 UTC, HIPPIEKICK commented on code/src/Header.js
> +import React from 'react';
Only one left! Approving now 👍

2021-03-09 11:25 UTC, closed without merging