Project Survey
Technigo/project-survey pull request #143
Opened 2020-10-29 16:44 UTC by JHarde

Link to my deployed project:

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2020-10-29 17:21 UTC, luuf81 approved these changes
Great work Joel! Nice and clean design and love the fact you tried something new with Material UI! 

Slider is red level requirement but still maybe something to fix?

2020-10-29 17:21 UTC, luuf81 commented on code/src/Form.js
> +import Summary from "./Summary";
separate external/internal imports next time :)

2020-10-29 17:21 UTC, luuf81 commented on code/src/Form.js
> +  const [question, setQuestion] = useState("Question1");
Good clear naming of state and functions 👍

2020-10-29 17:21 UTC, luuf81 commented on code/src/Form.js
> +  };
maybe comment on this function since it's not obvious to me what it does.

2020-10-29 17:21 UTC, luuf81 commented on code/src/Helper.js
> +  const isValidEmail = /\S+@\S+\.\S+/.test(email);
Regex validation 😍

2020-10-29 17:21 UTC, luuf81 commented on code/src/Form.js
> +      {question !== "Summary" ? (
Great use of ternary operator here but maybe keep it consistent and do it like you do on the other ones? "&&"

2020-10-29 17:21 UTC, luuf81 commented on code/src/Form.js
> +  const handleNextQuestion = (event) => {
no need for parenthesis when single argument

2020-10-29 17:21 UTC, luuf81 commented on code/src/Form.js
> +  };
no need for curly brackets when only one line of code

2020-10-29 17:21 UTC, luuf81 commented on code/src/Question1.js
> +const Question1 = ({ city, onCityChange }) => {
Destructuring props 🙌

2020-10-29 17:21 UTC, luuf81 commented on code/src/Question3.js
> +//               aria-labelledby="chocie a type of training"
Commented out code should be deleted :)

2020-10-29 17:21 UTC, luuf81 commented on code/src/index.css
> +} */
commented out => delete

2020-10-29 17:21 UTC, luuf81 commented on code/src/index.css
> +}
doing the same thing right? h2, h3 {}...

2020-10-29 17:21 UTC, luuf81 commented on code/src/index.css
> +  align-items: center; */
delete commented out code

2020-10-29 17:21 UTC, luuf81 commented on code/src/Question2.js
> +      />
This slider doesn´t seem to work correctly so either remove or fix? 😼 Love the effort!

2020-11-09 09:40 UTC, HIPPIEKICK commented on code/src/Question3.js
> +              checked={training.includes("Kickboxing")}
This is how you would deal with checkboxes, not radio buttons :) Radio buttons work like only one at a time should be selected.

2020-11-09 09:45 UTC, HIPPIEKICK requested changes
Great effort but some things need to be fixed:
- Radio buttons should act like radio buttons
- Range slider is not working properly (every other output shows 0 and no state is changing when the value is updated)
- Clean up your code (remove unused code)

2020-11-14 16:16 UTC, JHarde commented
Have done my best to implement the requested changes now, let me know if more is needed!

2020-11-16 09:30 UTC, HIPPIEKICK approved these changes

2021-03-09 11:25 UTC, closed without merging