Survey project
Technigo/project-survey pull request #149
Opened 2021-03-19 14:02 UTC by leelalaim

Link to my deployed project: https://friend-match.netlify.app/

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2021-03-23 09:26 UTC, matildasvensson85 reviewed
Really nice website turning the survey into a friend matching website. The requirements fpr blue level is well fulfilled. 

The code is well structured and organized, and easy to understand. The indentation and formatting looks good. There are some inconsistencies when it comes to semicolons and single or double quotes. The site is accessible, a lot of semantic tags are used, and the code is made  even more accessible through aria code. 

The styling looks really good and worked through, and the site is responsive. The only thing Im thinking that could possibly be changed is that when you resize the window, there is a moment where the text  is half on the black part of the screen, and half on the image. This makes the readability of the text not optimized, since the font color is white, and the colors of the sky is quite light as well.

2021-03-23 09:26 UTC, matildasvensson85 commented on code/src/App.js
> +import './index.css';
Sometimes semicolons are used and sometimes not

2021-03-23 09:26 UTC, matildasvensson85 commented on code/src/App.js
> +              type="submit"
Sometimes " is used and sometimes '

2021-03-23 09:26 UTC, matildasvensson85 commented on code/src/DropdownLocation.js
> +        <div className='dropdown-location'>
Can <section> be used here instead, to make the html more semantic?

2021-03-23 09:29 UTC, matildasvensson85 requested changes
Really nice website turning the survey into a friend matching website. The requirements fpr blue level is well fulfilled. 

The code is well structured and organized, and easy to understand. The indentation and formatting looks good. There are some inconsistencies when it comes to semicolons and single or double quotes. The site is accessible, a lot of semantic tags are used, and the code is made  even more accessible through aria code. 

The styling looks really good and worked through, and the site is responsive. The only thing Im thinking that could possibly be changed is that when you resize the window, there is a moment where the text  is half on the black part of the screen, and half on the image. This makes the readability of the text not optimized, since the font color is white, and the colors of the sky is quite light as well.

2021-03-25 16:42 UTC, KarolCislowski approved these changes
Great job! 
For the next step, it would be nice to look for info on how to validate users' inputs :)

also, you should revisit your styling:
![image](https://user-images.githubusercontent.com/50926159/112510193-7ead6800-8d91-11eb-8d95-a7a009fe7e93.png)

2021-03-25 16:42 UTC, KarolCislowski commented on code/src/App.js
> +import './index.css';
Clean your imports up :) 
1. internal imports from react
2. components from node_modules
3. your components
4. CSS and another imports

2022-09-02 09:46 UTC, closed without merging