week 10 survey project
Technigo/project-survey pull request #159
Opened 2021-03-20 16:58 UTC by Yennie-Leek

Link to my deployed project:

https://heuristic-albattani-176af8.netlify.app

My reflections on how this week's project turned out:

My biggest problem is that I still struggling with JS and now diving in to React. I have a hard time to understand the connections. 

This week has been a little bit better as I have gotten some help and guidance from my code coach. 
I did the first part on my own, but then got some help to connect the components to the Form and App files to be able to send data properly. 
Its been a lot of googling, watching the videos from Technigo and most of the help I got from my code coach. 

Things I'd like to have clarified or explained in more detail:

If I had more time I would go through the accessibility part more and try to make it optimised. There is some things that worked earlier (radiobuttons) and after some other changes it stop working and I can find out what the problem is. So I need to put some extra time in to it later to fix it.
Also I would have wanted to experiment with more functions, like range, progressbar and similar.

2021-03-24 13:23 UTC, annalenksjo requested changes
Hello Yennie! 
Really nice and colorful project, love that! I'm not the biggest ice cream lover my self though :P 
Everything seems to work as it should! 

Some things I suggest editing:

- Add cursor:pointer effect on the buttons
- Really like the background image! Although it make the text sligtly  difficult to read, especially if you have problems with vision   (especially the radio buttons). So maybe improve this in some way like   a background color on the text.
- Why is polka-option bold in the drop down? Is this intentional? I'm  curious why in that case - is it your favourite maybe? :P
 - Maybe remove the isResultCOmplete function I dont think it does  anything?



You mentioned that you had problems with your radiobuttons but I guess you fixed it because they worked fine for me! Maybe you will have time at some point to go back and add some of the extra functionality that you mentioned :) I wish the same for my project! Well done with 16 commits! You are really getting in to that habit! Well done!!

2021-03-24 13:23 UTC, annalenksjo commented on code/src/App.css
> +  height: 100vh;
This is interesting! I guess this is a part of your solution to show the last summary? What is it ::after really? I have mostly seen this on links where the after is then after click for example. Would be nice to add an explanatory comment?

2021-03-24 13:23 UTC, annalenksjo commented on code/src/App.css
> +justify-content: space-around;
the declarations should be indented :)

2021-03-24 13:23 UTC, annalenksjo commented on code/src/App.css
> +justify-content: space-around;
You have mixed a bit with indented and not indented so just correct where its not

2021-03-24 13:23 UTC, annalenksjo commented on code/src/App.css
> +  .fill-in-field {
Maybe add the same structure with headings in the media queries as well? Makes it a lot easier to follow!

2021-03-24 13:23 UTC, annalenksjo commented on code/src/App.css
> +  height: 30px;
remember that you can set css declarations for multiple classes if they have the same styling(or in part the same styling) so you can save some space! For example:
.again-btn,
.ice-pic {
   border:
   }
and then make the individual declarations on respective. Now it was only one in common in this example hehe but there are some classes above with more declarations in common !

2021-03-24 13:23 UTC, annalenksjo commented on code/src/Form.js
> +    }
I dont think you need this part since all the fields are required so its already checked at that point!

2021-03-25 17:58 UTC, KarolCislowski approved these changes
Great job!
Maybe for the next step, you will try to add some more exotic types of inputs? 🍹 🍨

2022-09-02 09:46 UTC, closed without merging