Project React survey
Technigo/project-survey pull request #173
Opened 2021-03-21 17:34 UTC by Ann-Sofi

Link to my deployed project:

https://book-survey-annsofi.netlify.app/

2021-03-23 20:12 UTC, CarolineF3 commented on code/src/App.js
> +  }
This is a very nice function!

2021-03-23 20:22 UTC, CarolineF3 commented on code/src/App.js
> +          <section className="many" id="many">
This className is a little bit vague, if the application was bigger it might be a bit hard to figure out what it stands for.

2021-03-23 20:25 UTC, CarolineF3 commented on code/src/App.js
> +    ):( // else if displaySummary is true
Nice with a clarifying comment on a long if statement. :)

2021-03-23 20:43 UTC, CarolineF3 commented on code/src/index.css
> +  background-image: url(./images/bookleaf.jpg);
I couldn't find an alt tag.

2021-03-23 21:10 UTC, CarolineF3 commented on code/src/Components/Header.js
> +      <div className="header">
You should avoid turning an HTML tag into a class.

2021-03-23 21:15 UTC, CarolineF3 commented on code/src/App.js
> +  }
I might be wrong about this but I think these functions could be put inside each(??) (respektive!) components sending the set functions as props.

2021-03-23 21:19 UTC, CarolineF3 requested changes
This is a very nice project, well done! The code is clean and easy to understand. :) The CSS file might need a little but of editing, using Beautify should do the trick.

2021-03-25 19:59 UTC, KarolCislowski approved these changes
Great job!
Maybe for the next step, you will try to add some more exotic types of inputs? 🍹

2022-09-02 09:45 UTC, closed without merging