Week 10, Survey tool - Therese Hagelin
Technigo/project-survey pull request #183
Opened 2021-03-21 20:43 UTC by ThereseHag

Link to my deployed project:
https://therese-survey.netlify.app/

My reflections on how this week's project turned out:
The work has proceeded in a good way. I started with creating header and footer components, followed by a basic form structure, and then added mapping, statements and summary. I had some issues when trying to deploy it, but after getting the advice to fix all warnings in the terminal before deploying, it all worked out fine. I like React a lot, even if there is still so very much to learn and a lot of information to process. 

Things I'd like to have clarified or explained in more detail:
I would like to get a better understanding of how to work with checkbox inputs, but will make sure to study that after this weeks project. Also, I'm always interested in getting a better understanding on how to use map method, even if it worked out well this time.

2021-03-24 18:50 UTC, MarySparrow requested changes
Great job on this project Therese! Not a single warning on the accessibility validation, way to go! ✨  Be proud of what you have accomplished! 🔥🔥🔥

2021-03-24 18:50 UTC, MarySparrow commented on code/src/Components/Form.js
> +
Great naming here, easy to understand what its for. 👍

2021-03-24 18:50 UTC, MarySparrow commented on code/src/Components/Form.js
> +    }
Nice that you give the reason to a user why its not submitting 👌 , always frustrating when not working.

2021-03-24 18:50 UTC, MarySparrow commented on code/src/Components/Form.js
> +
To make it same pattern as above return, remove this empty line after return💡

2021-03-24 18:50 UTC, MarySparrow commented on code/src/Components/Form.js
> +      </div>
Please have a look at the indentation here, it's a little bit off. I would suggest you to move in {timeChoice.....} and maybe also {time}.  The input tag I would also suggest to move in. On line 69 close tag should go one step to the left <-- to match the input opening tag.  On line 73 I would put the (({ to match the opening of the {timeChoice...}. Am I being confusing? hope not 🙃

2021-03-24 18:50 UTC, MarySparrow commented on code/src/Components/Form.js
> +          <option>Sales</option>
Remember to keep the same pattern 🏳️‍🌈, the first option has no space between the next option. All together or all with line space will look more clean.

2021-03-24 18:50 UTC, MarySparrow commented on code/src/Components/Form.js
> +          ))}
indentation 👀 (see above comment)

2021-03-24 18:50 UTC, MarySparrow commented on code/src/Components/Header.js
> +import React from 'react'
consistency on the endings here` ; `put them on all or none . I struggle with the same cant decide 🤷‍♀️

2021-03-24 18:50 UTC, MarySparrow commented on code/src/index.css
> +}
in larger project its always a good practice to have classes on all styling components👩‍🏫

2021-03-24 18:50 UTC, MarySparrow commented on code/src/index.css
> +  top: 30px;
Really liked your circles, it brings a nice touch to the survey 🤩 🤩

2021-03-24 18:50 UTC, MarySparrow commented on code/src/index.css
> +}
remove empty line

2021-03-24 18:50 UTC, MarySparrow commented on code/src/index.css
> +  display: flex;
cleaning cleaning 🚿

2021-03-24 18:50 UTC, MarySparrow commented on code/src/index.css
> +  font-size: 20px;
If you have more time to put in this project maybe add some media queries to make it responsive in mobile view.

2021-03-27 12:49 UTC, KarolCislowski approved these changes
Great job!
You should read a little about how to stick your footer to the bottom of the page 🤓 
Maybe for the next step, you will try to add some more exotic types of inputs? 🍹

2022-09-02 09:45 UTC, closed without merging