Week 10 project Survey - Malin Göthe
Technigo/project-survey pull request #184
Opened 2021-03-21 20:53 UTC by M4L5

Link to my deployed project:
https://agitated-wing-781431.netlify.app

My reflections on how this week's project turned out:
Well, I managed to make the survey work, but I know I need to make it better. 

Things I'd like to have clarified or explained in more detail:
How to use props when one wants to add a profile image. 
Otherwise I just need to practice, practice, practice.

2021-03-24 20:39 UTC, Frivridna requested changes
Malin! 
Great job with the survey, and nice to hear you have a code mentor that provided help upon request :)  

Your code is clean and you did an amazing job with color and shapes in the header! I can see that that week's Labs in our team was useful, I thought so too!🙂 

Styling: 
The form section is really nice for tablet and desktop, just need to do it for mobile view🙂 if you like to put some energy into it? Consider adding tabindex and aria-label's where it's needed to meet this week's requirement "Your site should follow accessibility guidelines".  And I really want to see that Frasse pic in action as a profile image! 

Keep up the good learning curve Malin, you've come far in your journey, I am looking forward to seeing your coming projects. Remember this is only the first two week's with React and everything is new. We have the rest of the bootcamp to practice together!

2021-03-24 20:39 UTC, Frivridna commented on code/src/components/Form.js
> +                    setTimeout(console.log(instrument), 1000)
I am curious why you added the 
```javascript 
setTimeout(console.log(instrument), 1000)
```
method here? 

When I look in the console, I see my previous choice and not my current choice. What functionality did you want to add by setting it here? :)

2021-03-24 20:39 UTC, Frivridna commented on code/src/components/Form.js
> +        {showForm ?
Great job with Hiding and showing the Summary with the ternary operator!

2021-03-24 20:39 UTC, Frivridna commented on code/src/components/Form.js
> +}>
I love that your code is clean. It could become even cleaner with some indentation check for Form.js :)

2021-03-24 20:39 UTC, Frivridna commented on code/src/components/Header.css
> +  .header-accessory {
Nicely done with the circles (or sun's which was the first word that popped up to me when viewing them), consider giving them more descriptive names? :)

2021-03-24 20:39 UTC, Frivridna commented on code/src/components/SummaryOfForm.js
> +const SummaryOfForm = ({nameData, musicianData, instrumentData}) => {
Nice and descriptive destructuring here!

2021-03-27 12:52 UTC, KarolCislowski approved these changes
Great job! 
For the next step, it would be nice to look for info on how to validate users' inputs :)

2022-09-02 09:45 UTC, closed without merging