Project Survey - Felicia Liabäck Löwstett
Technigo/project-survey pull request #185
Opened 2021-03-21 20:56 UTC by liaback-lowstett

Link to my deployed project:

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2021-03-26 13:34 UTC, Sofarz approved these changes
Really good job on the survey project! Way to go on using useEffect and useCallback before we even started going through this :).

The website looks nice and clean, however adding a restart button in the summary would have been a nice touch in case the user would want to fill in your survey over and over again :).

2021-03-26 13:34 UTC, Sofarz commented on code/src/Components/Summary.js
> +            You paragraph project was the <span className="answer-text">{project}</span>.
You probably mean your favourite :)

2021-03-27 12:56 UTC, KarolCislowski requested changes
Please add the Netlify link so I can test it 😸

2021-03-27 15:44 UTC, Sofarz commented
https://youthful-almeida-30dc8d.netlify.app/

2021-03-28 04:56 UTC, KarolCislowski approved these changes
Great job!
Maybe for the next step, you will try to add some more exotic types of inputs? 🍹

2021-03-28 04:56 UTC, KarolCislowski commented on code/src/Components/Form.js
> +    <form
You should have only one return section inside of your component. You can achieve the same effect with a structure like this:
``` jsx 
  return (
    <>
       { submitted ? 
           <Summary />
             :
           <form>...
        }
    </>
  )
```

2022-09-02 09:45 UTC, closed without merging