pull request noemi
Technigo/project-survey pull request #186
Opened 2021-03-21 21:15 UTC by NoemiSalome

Link to my deployed project: https://noemi-project10-survey-react.netlify.app/

My reflections on how this week's project turned out: 
This weeks project feels like a combination of luck and coincidence. I don't feel like I understand what is going on in my messy code and am missing a structured approach this week. I mean the form is obviously working, but the thing behind it is just a mess - not only my code, but also my understanding 🤓😅

Things I'd like to have clarified or explained in more detail: 
I would love some hints for a cleaner approach. With which steps should I start? Building everything in one file and move them then in components or start with the components and then the mainfile (this is what I did this week). But with mine approach I felt like I was hopping back'n'forward a lot.

2021-03-24 20:45 UTC, ThereseHag requested changes
Very well done Noemi, you've done a great job with this project and I really like the look of your website. Most changes are definitely optional and just to see as suggestions, but I think it would be good to add content to the label in the form in order to get rid of the error in accessibility test. Could also be good to take a look at the size of radio button and text in mobile view to see if it should be a bit larger. 

Be proud of yourself, this is really great!

2021-03-24 20:45 UTC, ThereseHag commented on code/src/CharachteristicsButtonOption.js
> +    console.log(e.target.value)
In order to keep code clean, make sure to remove console.log before publishing :)

2021-03-24 20:45 UTC, ThereseHag commented on code/src/CharachteristicsButtonOption.js
> +                        onInputCharacteristicsChanged(e);
Really nice that you're dividing the input on separate lines, since it makes code easier to read and follows best practice.

2021-03-24 20:45 UTC, ThereseHag commented on code/src/components/Input.js
> +            <label htmlFor={nameValue}></label>
There is no content in this label, which also gives an error in the accessibility check in WAVE. Could be good to update to have some content going in there :)

2021-03-24 20:45 UTC, ThereseHag commented on code/src/index.css
> +  margin-top: 5px;
The text is very small under the radio buttons. It works in the computer, but in mobile view it's a bit tricky to see.

2021-03-24 20:45 UTC, ThereseHag commented on code/src/index.css
> +  margin: 0;
The radio buttons look good in the computer but see to be very small in mobile. Maybe they could be a bit larger for mobile view in order to improve the accessibility?

2021-03-24 20:45 UTC, ThereseHag commented on code/src/components/Survey.js
> +    const [summary, setSummary] = useState(false)
Good job with naming, it's easy to understand what they will be used for.

2021-03-24 20:45 UTC, ThereseHag commented on code/src/components/Select.js
> +            </div>
Nice job with indentation here. Looks clean.

2021-03-24 20:45 UTC, ThereseHag commented on code/src/components/Survey.js
> +                                        )}
Nice job with the map method!

2021-03-24 20:45 UTC, ThereseHag commented on README.md
> +https://noemi-project10-survey-react.netlify.app/
It looks really nice and the topic is real fun. Love the colors :)

2021-03-24 20:45 UTC, ThereseHag commented on README.md
> +This weeks project was about building a survey form with react. The user fills out the form and by submitting getting a summery of the answer displayed. The form consist three different question type
Good job with all of them!

2021-03-24 20:45 UTC, ThereseHag commented on code/src/components/Summary.js
> +            </p>
Nice to see that you are using classes to style instead of styling the paragraph itself.

2021-03-24 20:45 UTC, ThereseHag commented on code/src/index.css
> +}
In general, it  can be good to create a class for the paragraphs and style class in order to make it easier to handle for larger projects. This approach is still possible to work with as long as the project is quite small :)

2021-03-27 13:01 UTC, KarolCislowski approved these changes
Great job!
Please make your font bigger 🤓 
Maybe for the next step, you will try to add some more exotic types of inputs? 🍹

2022-09-02 09:45 UTC, closed without merging