maria sparre project survey
Technigo/project-survey pull request #192
Opened 2021-03-21 22:10 UTC by MarySparrow

Link to my deployed project:  https://optimistic-stonebraker-71d34e.netlify.app

My reflections on how this week's project turned out: 

Not so well as I hoped, did not understand the way to combine the components, but still really like React for how it simplifies things, just need to get how to :) 

Things I'd like to have clarified or explained in more detail:
How can I separate the Form into components?
how to show one question at the time, best practice to do it?
Please help me understand the things I have commented in the code 
-How do I align the radio buttons with text?

2021-03-24 13:22 UTC, Irina-web-dev requested changes
This is a very nice and clean website with easy to understand code behind it. Good job Maria! We do not always have to over style a website for it to look nice. Sometimes less is more ✨

As you have already mentioned some things needs to fixed like making radio buttons and text on the same line, creating at least one more component just to get the understanding on how to work with components and pass props. I have tried to give some advise on these questions, hope it will help you.

How do you think maybe at least media query for a mobile view would make your app more responsive and look nice on the small mobile device as well?

Have a great day 🦊
Irina

2021-03-24 13:22 UTC, Irina-web-dev commented on code/README.md
> +- how to show one question at the time, best practice to do it?
I did it like this:
     1. Define a state to update the current question: const [question, setQuestion] = useState(0)
     2. Function that will update the state:   const onNextQuestionChange = () => {
                                                                         setQuestion(question + 1)
                                                                     }
     3. Create a button that will call this function each time it is clicked: 
    <button onClick={onNextQuestionChange}> Next <button>
     4. Use the conditional for each question: 
     {question === 0 && (
<div className="container-input-fields">
        <div className="name-label">
          <label htmlFor={name}>Number of tickets:</label>
          <input 
            className="name-input" 
            id="name" 
            type="number" 
            value={name} 
            onChange={onNameChange}
          /> 
        </div>
          <button onClick={onNextQuestionChange}> Next <button>)
}

2021-03-27 13:39 UTC, KarolCislowski requested changes
It is a great project, but please fix these radio buttons issue :)

2021-03-27 23:33 UTC, MarySparrow commented on code/src/index.css
> +  width: 100%;
Great feedback Irina, I have made it work with your help and some padding and removed margins :) good stuff!

2021-03-27 23:35 UTC, MarySparrow commented on code/src/components/Form.js
> +          {date}   {/*why is this needed?? */}
Hello, this I actually know, the confusion is why it is needed there in that position. It makes no sense to me. between two tags? The `{date }` is already mentioned in another place so why again... any input there to understand this better? ⭐

2021-03-28 04:36 UTC, KarolCislowski approved these changes
Great work 🥳

2021-10-20 14:25 UTC, closed without merging