structure
Technigo/project-survey pull request #195
Opened 2021-03-21 22:33 UTC by nazi-pira

Link to my deployed project:

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2021-03-24 19:29 UTC, takrami approved these changes
I'm impressed by your code specially CSS part :1st_place_medal: 
I couldn't find your live website. Your project should have a deploy version. Other than I don't have a lot of things to say. Great job :100: 
I put some minor comments as suggestions.

2021-03-24 19:29 UTC, takrami commented on code/src/App.js
> +import { Survey } from './components/Survey'
Well structured and clean file! :+1:

2021-03-24 19:29 UTC, takrami commented on code/src/components/Summary.js
> +  const result = () => {
Great idea! :100:

2021-03-24 19:29 UTC, takrami commented on code/src/components/Summary.js
> +
The white spaces can be deleted.

2021-03-24 19:29 UTC, takrami commented on code/src/components/Summary.js
> +          <p className="correct-answer">{props.answers.spots === props.hangoutSpot ? "" : `Correct answer: ${props.answers.spots}`}</p>
You can break lines here(after p tag). It would be more readable.

2021-03-24 19:29 UTC, takrami commented on code/src/components/survey.css
> +.form-style {
Really great styling! :+1:

2021-03-24 19:29 UTC, takrami commented on code/src/index.css
> +footer {
It's better to use classes for styling. It's not good practice style tags directly.

2021-03-27 13:58 UTC, KarolCislowski requested changes
Please add the Netlify link so I can test your app.

2021-05-22 09:59 UTC, KarolCislowski approved these changes
👍🏻

2021-10-20 14:25 UTC, closed without merging